### ISSUE TITLE
Curse of Ignorance doesn't work correctly with some blocks

### ISSUE THREAD

**Issue by TheDirectorX** [Darkhax-Minecraft/Cursed#5]
Even if it is preferable to break the block with this tool, it still significantly affects the durability. At the same time, `The One Probe` correctly determines the tool for this type of block. And so with all the tools.

![2020-03-14_21 53 46](https://user-images.githubusercontent.com/43481085/76686704-35372280-663f-11ea-90c1-5f10008cadbe.png)
![2020-03-14_21 53 54](https://user-images.githubusercontent.com/43481085/76686705-37997c80-663f-11ea-85be-620ee3736946.png)

**Comment by Darkhax** [comment]
Thanks for reporting this issue. This one was a nice rabbit hole. The TL;DR is that Forge defines the tool type for vanilla blocks but has forgotten to add support for new vanilla blocks in the last few major updates. Looking at The One Probe's code McJty ran into this issue as well however instead of implementing the proper detection code he implemented code that simulates breaking the block with different types of wooden tools. I've fixed the issue with my enchantment by implementing the proper detection code however The One Probe should not be trusted as a definitive source on when blocks are harvestable.
